# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true
bind-address: '*'
# 此功能仅在 allow-lan 设置为 true 时生效，支持三种参数：
#  '*'                            绑定所有的 IP 地址
# 192.168.122.11                绑定一个的 IPv4 地址
# Clash 路由工作模式

# 规则模式：rule（规则） / global（负载均衡）/ direct（全局直连）
mode: rule

# Clash 默认将日志输出
log-level: info

# clash 的 Restful API 监听地址
external-controller: '0.0.0.0:9090'

# RESTful API 的口令 (可选)
# secret: ""

# DNS 服务器配置(可选；若不配置，程序内置的 DNS 服务会被关闭)
dns:
  enable: true
  nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 114.114.114.114
  fallback:
    - 223.5.5.5

cfw-bypass:
  - qq.com
  - taobao.com
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000

proxies:


proxy-groups:
  - name: "全局代理"
    type: select
    proxies: [ "负载均衡", "失败切换", "延迟最低" ]

  - name: 失败切换
    type: fallback
    interval: 300
    url: 'http://www.gstatic.com/generate_204'
    proxies:

  - name: 延迟最低
    type: url-test
    interval: 300
    url: 'http://www.gstatic.com/generate_204'
    proxies:

  - name: 负载均衡
      type: load-balance
      interval: 300
      url: 'http://www.gstatic.com/generate_204'
      proxies:

rules:
  # 抗 DNS 污染
  - DOMAIN-KEYWORD,amazon,失败切换
  - DOMAIN-KEYWORD,google,失败切换
  - DOMAIN-KEYWORD,gmail,失败切换
  - DOMAIN-KEYWORD,youtube,失败切换
  - DOMAIN-KEYWORD,facebook,失败切换
  - DOMAIN-KEYWORD,twitter,失败切换
  - DOMAIN-KEYWORD,instagram,失败切换
  - DOMAIN-KEYWORD,dropbox,失败切换
  - DOMAIN-KEYWORD,blogspot,失败切换
  - DOMAIN-KEYWORD,whatsapp,失败切换
  - DOMAIN-SUFFIX,fb.me,失败切换
  - DOMAIN-SUFFIX,fbcdn.net,失败切换
  - DOMAIN-SUFFIX,twimg.com,失败切换
  - DOMAIN-SUFFIX,youtu.be,失败切换

  # 常见广告域名屏蔽
  - DOMAIN-KEYWORD,admarvel,REJECT
  - DOMAIN-KEYWORD,admaster,REJECT
  - DOMAIN-KEYWORD,adsage,REJECT
  - DOMAIN-KEYWORD,adsmogo,REJECT
  - DOMAIN-KEYWORD,adsrvmedia,REJECT
  - DOMAIN-KEYWORD,adwords,REJECT
  - DOMAIN-KEYWORD,adservice,REJECT
  - DOMAIN-KEYWORD,domob,REJECT
  - DOMAIN-KEYWORD,duomeng,REJECT
  - DOMAIN-KEYWORD,dwtrack,REJECT
  - DOMAIN-KEYWORD,guanggao,REJECT
  - DOMAIN-KEYWORD,lianmeng,REJECT
  - DOMAIN-KEYWORD,omgmta,REJECT
  - DOMAIN-KEYWORD,openx,REJECT
  - DOMAIN-KEYWORD,partnerad,REJECT
  - DOMAIN-KEYWORD,pingfore,REJECT
  - DOMAIN-KEYWORD,supersonicads,REJECT
  - DOMAIN-KEYWORD,uedas,REJECT
  - DOMAIN-KEYWORD,umeng,REJECT
  - DOMAIN-KEYWORD,usage,REJECT
  - DOMAIN-KEYWORD,wlmonitor,REJECT
  - DOMAIN-KEYWORD,zjtoolbar,REJECT
  - DOMAIN-SUFFIX,mmstat.com,REJECT

  # LAN
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT

  # 最终规则
  - GEOIP,CN,DIRECT
  - MATCH,失败切换
